config/routes.rb
Rails.application.routes.draw do

  root 'companies#index'

    resources :companies do
      member { post :import_data }
    end

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :company_datum

  validates :company_name, :presence => true, :uniqueness => true

  def grouped_monthly
    self.company_datum.all.group_by { |t| t.date.beginning_of_month }
  end

  def import(file)
    CSV.foreach(file.path, headers: true) do |row|
      new_hash = {'company_id' => self.id}

      # Transform data to enter into db nicely
      row.to_hash.each_pair do |k,v|
        # Handle formatting of date
        if ( k == 'date' )
          new_hash.merge!({'date' => Date.strptime(v, '%m/%d/%Y')})
        else
          # Handle transform of header row to make space and dash into underscore
          new_hash.merge!({k.tr(' ', '_').tr('-','_') => v})
        end
      end

      begin
        company_datum = CompanyDatum.create! new_hash.to_hash
      rescue

      end
    end
  end

end

app/models/company_datum.rb
class CompanyDatum < ActiveRecord::Base

  belongs_to :company

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all.order('id desc').paginate(:per_page => 10, :page => params[:page])
  end

  def show
    @company = Company.find(params[:id])

    @company_datum = @company.company_datum.order(sort_column + " " + sort_direction).paginate(:per_page => 20, :page => params[:page])
    @grouped_datum = @company.grouped_monthly
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.create(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render action: "new", notice: 'Company name already exists'
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update_attributes(params[:company])
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_url
  end

  def import_data
    @company = Company.find(params[:id])
    # puts "LOOK HERE ---> #{params[:file]}"
    if @company.import(params[:file])
      redirect_to @company, notice: 'Data import successful.'
    else
      redirect_to @company, notice: 'Data import not succcessful.'
    end

  end

  private
    def company_params
      params.require(:company).permit(:company_name)
    end

     def sort_column
      CompanyDatum.column_names.include?(params[:sort]) ? params[:sort] : "date"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(params[:company])

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update_attributes(params[:company])
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    # css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end

end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/index.html.erb
<div id="mainBody">

  <ul class="nav nav-tabs">
    <li role="presentation"><a href="/">Home</a></li>
  </ul>

  <br>

  <div>
    <table class="table table-hover">
      <th>Company Name</th>
      <th>Data Rows</th>

      <% @companies.each do |company| %>
        <tr>
          <td><%= link_to(company.company_name, :controller => 'companies', :action => 'show', :id => company.id) %></td>
          <td><%= company.company_datum.length %></td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate @companies, renderer: BootstrapPagination::Rails %>
  </div>

  <%= button_to "Add Company", new_company_path, :class => "btn btn-default", :method => :get %>

</div>

app/views/companies/new.html.erb
<div id="mainBody">

  <ul class="nav nav-tabs">
    <li role="presentation"><a href="/">Home</a></li>
    <li role="presentation" class="active"><a href="#">Create New Company</a></li>
  </ul>

  <br/>

  <% if @company.errors.present? %>
    <div class="alert alert-danger" role="alert"><%= @company.errors.full_messages.first %></div>
  <% end %>

  <%= form_for @company do |f| %>
    <div class="form-group">
      <%= f.label :company_name %>
      <span>
        <%= f.text_field :company_name, :class => "form-control", :placeholder => "Company" %>
      </span>
    </div>
    <%= submit_tag "Submit", class: "btn btn-default" %>
  <% end %>

</div>

app/views/companies/show.html.erb
 <div id="mainBody">

  <ul class="nav nav-tabs">
    <li role="presentation"><a href="/">Home</a></li>
    <li role="presentation" class="active"><a href="#"><%= @company.company_name %></a></li>
  </ul>

  <br>

  <div class="form-group">
    <label>File input</label>
    <%= form_tag import_data_company_path, multipart: true, class: "form-inline" do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import", class: "btn btn-default", disabled: true %>
    <% end %>
  </div>

  <table class="table table-hover">
    <tr>
      <th>Month/Year</th>
      <th>Total Pre-Tax Amount</th>
      <th>Total Tax Amount</th>
    </tr>
    <% @grouped_datum.sort.each do |month, data| %>
      <% total_pre_tax_amount = 0 %>
      <% total_tax_amount = 0 %>
      <% for datum in data %>
        <% total_pre_tax_amount += datum.pre_tax_amount %>
        <% total_tax_amount += datum.tax_amount %>
      <% end %>
      <tr>
        <td><%= month.strftime('%B %Y') %></td>
        <td><%= total_pre_tax_amount %></td>
        <td><%= total_tax_amount %></td>
      </tr>
    <% end %>
  </table>


  <table class="table table-hover">
    <tr>
      <th><%= sortable "date", "Date" %></th>
      <th><%= sortable "category", "Category" %></th>
      <th><%= sortable "employee_name", "Employee Name" %></th>
      <th><%= sortable "employee_address", "Employee Address" %></th>
      <th><%= sortable "expense_description", "Expense Description" %></th>
      <th><%= sortable "pre_tax_amount", "Pre-tax Amount" %></th>
      <th><%= sortable "tax_name", "Tax Name" %></th>
      <th><%= sortable "tax_amount", "Tax Amount" %></th>
    </tr>

    <% @company_datum.each do |company_data| %>
      <tr>
        <td><%= company_data.date %></td>
        <td><%= company_data.category %></td>
        <td><%= company_data.employee_name %></td>
        <td><%= company_data.employee_address %></td>
        <td><%= company_data.expense_description %></td>
        <td><%= company_data.pre_tax_amount %></td>
        <td><%= company_data.tax_name %></td>
        <td><%= company_data.tax_amount %></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @company_datum, renderer: BootstrapPagination::Rails %>

</div>

<script>

$(document).ready(
    function(){
        $('input:file').change(
            function(){
                if ($(this).val()) {
                    $('input:submit').attr('disabled',false);
                }
            }
            );
    });

</script

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waveapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>